### ISSUE TITLE
zipfile internal folders

### ISSUE THREAD

**Issue by matt-farmer** [nsip/sif-xml2json#2]
When downloading the zip files from releases, they unpack to folders with just the operating system name e.g.
mac, win, linux.

Our convention is to have the top-level folder follow the product name so sif-xml2json in this case, ideally with the version number so top-level becomes if-xml2json-0-1-5 in this case. 
This means later versions don't overwrite so users can see/use/discard earlier versions as they see fit.
Code to demonstrate this is in the common tools area of most of our projects, take a look at build.sh, release.sh and /tools/release.go in nsip/nias2 for working examples.

**Comment by cdutwhu** [comment]
Done, see updated release packages.
